### PR TITLE
delivery timings on aggdata

### PR DESCRIPTION
**Pull request by areedv**

### CODE REVIEW

**Comment by areedv** [comment]
https://github.com/mong/qmongjs/issues/35

**Review by arnfinn — APPROVED** [review]

**Comment by areedv** [comment]
Haha @arnfinn , du føler kanskje tidspress? Ikke helt ferdig ennå, men snart...

**Comment by areedv** [comment]
This change requires an update to the data model, _i.e._
```sql
ALTER TABLE
  `agg_data`
ADD COLUMN IF NOT EXISTS
  `delivery_time` timestamp NULL DEFAULT NULL
AFTER `dg`;
```

**Comment by areedv** [comment]
> ```sql
> ALTER TABLE
>   `agg_data`
> ADD COLUMN IF NOT EXISTS
>   `delivery_time` timestamp NULL DEFAULT NULL
> AFTER `dg`;
> ```

have been run on all instances

**Pull request merged**
